sudo: required

language: cpp

services:
  - docker

before_install:
  - docker build -t test_ngraph -f .ci/travis/ubuntu/Dockerfile .

install: true

script:
  - docker run -w '/root/ngraph/build' test_ngraph make check
  - docker run -w '/root/ngraph/python' test_ngraph tox -e py27
  - docker run -w '/root/ngraph/python' test_ngraph tox -e py35

branches:
  only:
    - "master"
